ponkotuy/MyFleetGirls

library/src/main/scala/com/ponkotuy/data/Basic.scala, server/app/models/db/Admiral.scala, server/app/models/db/Basic.scala, server/app/views/index.scala.html, server/app/views/user/head_content.scala.html, server/conf/db/migration/default/V74__add_medals.sql
MariaDB の環境用意するの面倒だったので一切テストしてないです。多分動かない。
あと UI もハリボテです。
=> プレイヤーがじゃぶじゃぶ課金したくなるような射幸心を煽りまくる甲勲章表示機能の仮実装

server/app/models/join/DeckSnapshotWithShip.scala, server/app/views/user/snapshot.scala.html
=> スナップショット作成時刻の表示

.travis.yml, client/build.sbt, library/build.sbt, profiler/build.sbt, project/Build.scala, server/build.sbt, tester/build.sbt
=> bump-scala-version-2.11.6

project/Build.scala, update/src/main/java/Main.java
今までの比較対象：ファイルサイズ
この変更での比較対象：最終更新時間
=> ダウンローダーの改修（ 更新チェックを更新時間で比較・圧縮転送に対応）

client/build.sbt, client/src/main/scala/com/ponkotuy/http/MFGHttp.scala, client/src/main/scala/com/ponkotuy/run/Main.scala, package/resources/application.conf.sample, update/src/main/java/Connection.java, update/src/main/java/Main.java, update/src/main/java/MyTrustManager.java, update/src/main/java/MyVerifier.java
=> Enable https

server/app/views/Js.scala
PR 作り直した。
master ブランチ自体がよく分からないことになってて辛かった :disappointed_relieved:
=> Heroku への link を https に。

client/src/main/scala/com/ponkotuy/http/MFGHttp.scala
Reverts ponkotuy/MyFleetGirls#180
=> Revert "POST メソッドの時もリダイレクトを有効にするように設定"

server/build.sbt
=> Remove redundant module definition

client/src/main/scala/com/ponkotuy/http/MFGHttp.scala
ちょこっとだけパフォーマンスチューニング。
本当は持続的接続したかったけど流石にサーバー負荷が戸惑われたので明示的に 0 に設定。
=> HTTPClient を ThreadSafe な実装にして使い回せるように。

client/src/main/scala/com/ponkotuy/http/MFGHttp.scala, update/src/main/java/Connection.java
=> アップデーターとクライアントからの通信に User-Agent を設定。

client/src/main/scala/com/ponkotuy/http/MFGHttp.scala
=> UserAgent の設定ミス修正

maintenance/hooks/post-receive
なお環境が無いのでテストはしてない（）
あくまで参考程度のつもりなので、見飽きたら reject なりで close してくれて良いよ
=> デプロイスクリプトをちょっと書き換えてみた

.gitignore, .travis.yml, project/Build.scala
=> Add down lib

server/app/models/db/ShipHistory.scala, server/conf/db/migration/default/V113__speedup_ship_history.sql
ship_historyの高速化の為にpartitionを入れる #288 
10/9のメンテ時にmigrationをする(10分ほど掛かるので)
=> Speedup ship_hisotry by using partition

server/app/models/join/ShipParameter.scala
http://wikiwiki.jp/kancolle/?%B4%CF%BA%DC%B5%A1%BD%CF%CE%FD%C5%D9#Effect
によると、熟練度最大時の制空値上昇は
艦戦 25
艦攻、艦爆 3
水上爆撃機 9
程度らしい
=> Fix calculation of airSuperiority

project/Build.scala
wgetのないOSもあるんですよ！
具体的にはWindowsとか
=> Use sbt.IO to download the library

client/src/main/scala/com/ponkotuy/restype/PictureBook.scala, library/src/main/scala/com/ponkotuy/data/Book.scala
=> Fixes #254 : parse null books

server/app/honor/SpecialDay.scala
終戦記念日～クリスマスの間が大きくあいていて、間に何か欲しいなと思ったので。
秋刀魚漁をやってたのでハロウィンはやらないのかと思ったので控えていたけれど、
小規模でもハロウィンをやるのならば、称号にも有ってもいいかなと。
=> 称号へのハロウィンの追加

server/conf/db/migration/default/V117__fix_cell_info.sql
#307 にミスがあったのでそれの修正です。
* E3 ボスの位置は 10(J) ではなく 11(K)
* E5 2(B) は start ではない
=> 2015秋イベントデータの修正

server/app/Global.scala, server/app/models/db/Basic.scala, server/app/models/db/CalcScore.scala, server/app/models/db/CellInfo.scala, server/app/models/db/MapInfo.scala, server/app/tool/BattleScore.scala, server/app/util/Cron.scala, server/conf/db/migration/default/V118__speedup_battle_score.sql, server/conf/db/migration/default/V119__create_calc_score.sql
=> Add battle score calculator

library/src/main/scala/com/ponkotuy/value/ShipIds.scala, server/app/honor/Fetishism.scala
=> メガネフェチに沖波を追加

server/app/honor/InitShip.scala, server/app/honor/ShipMaxLv.scala
=> 最大レベルが155に上がった事への対応 (称号絡み)

package/resources/MyFleetGirls.command, package/resources/MyFleetGirls.sh
ディレクトリ名に空白が含まれる時の問題への対処です
https://twitter.com/dyingalive__/status/717160961128292352
=> ディレクトリ名に空白が含まれる場合の対処

project/Build.scala, project/plugin.sbt
SBTプラグインのバージョン更新
scalikejdbc-mapper-generatorはserverの依存バージョンに合わせてある
=> Update sbt plugins

server/app/tool/AirSuperiorityWithSlot.scala, server/app/tool/EquipType.scala
水上戦闘機を追加。
熟練度による制空値はもっと細かく判明しているようなので、またPRする予定。
=> Add Seaplane Fighter

.dockerignore, Dockerfile, docker-compose.yml, docker/db/Dockerfile, docker/db/enable-mroonga.sql
* docker-composeのformat version 2対応
* Java用コンテナでAlpine Linuxベースのimageを利用するように変更
* MariaDBのMroonga pluginを有効化
=> Update docker files

server/app/tool/AntiAirCutin.scala
対空カットイン装備に追加
* Bofors 40mm四連装機関砲
* QF 2ポンド8連装ポンポン砲
三連装集中配備と同じ効果がある
=> Add cut-in equipments

server/app/models/join/ShipSnapshotWithName.scala, server/app/tool/AirSuperiority.scala, server/app/tool/EquipType.scala
=> Add improvement bonus of aircraft

project/coffeelint.json, sideci.yml
=> Add SideCI

project/coffeelint.json, sideci.yml
Reverts ponkotuy/MyFleetGirls#379
=> Revert "Add SideCI"

client/src/main/java/com/ponkotuy/http/MFGKeyStore.java, client/src/main/scala/com/ponkotuy/http/PostActor.scala, client/src/main/scala/com/ponkotuy/proxy/LittleProxy.scala
=> StackTrace を SLF4J 経由で出力するように変更。

client/src/main/resources/logback.xml
=> console への出力で改行がうまく出来ていなかったのを修正。

server/conf/db/migration/default/V140__fix_cell_info.sql
=> 2017冬イベント E1ボス位置修正

client/build.sbt
LittleProxy release note.
https://github.com/adamfisk/LittleProxy/releases/tag/littleproxy-1.1.2
=> Update LittleProxy to 1.1.2

server/conf/db/migration/default/V142__add_event_recort.sql
=> 2017春イベント名追加

library/src/main/scala/com/ponkotuy/value/ShipIds.scala, server/app/honor/Fetishism.scala
=> 眼鏡っ子に天霧を追加。

server/app/views/proxy.scala.html
=> 括弧の閉じ忘れを修正。

project/plugin.sbt
[$git_branch] $project_name: 
な感じになるぞ（色も付く）
=> sbt の prompt を設定

client/build.sbt, library/build.sbt
さし当たり影響の少なそうな物、主にメンテナンスリリースのみ。
各ライブラリのChangeLogを見る限り大丈夫なはず。
- com.typesafe.config
- org.slf4j
- ch.qos.logback
- org.fusesource.jansi
=> library の更新

server/conf/db/migration/default/V147__add_event_record.sql
=> 2017 秋イベント名追加

server/conf/db/migration/default/V151__add_event_record.sql
2/16開始と日程も発表されたので、とりあえず作戦名の追加です。
=> 2018 冬イベント名追加
