ponkotuy/MyFleetGirls

client/src/main/scala/com/ponkotuy/http/MFGHttp.scala
HttpClient はデフォルトでは POST リクエストに対する 301,302 等のレスポンスコードには従わない。
おそらく「 RFC 的には POST のままリダイレクトすべき・しかし既存の実装の多くは GET でリダイレクトしてしまう」という状況をみて、コーディング側で対処しろと言う事と思われる。
で、いくつかの情報をあたったところ Redirect に対するポリシー的な部分（RedirectStrategy）を置き換えてやれば良いとのこと。
素直には出てこないが LaxRedirectStrategy が同梱されており、ソースを見る限り以下の挙動となっており、目的に一番マッチしている。
* 対象は GET / POST / HEAD リクエスト
* 対応するレスポンスコードは 301, 302, 303, 307
参考情報
http://www.baeldung.com/httpclient-redirect-on-http-post
https://apache.googlesource.com/httpclient/+/trunk-adaptive-connpool/httpclient/src/main/java/org/apache/http/impl/client/LaxRedirectStrategy.java
=> POST メソッドの時もリダイレクトを有効にするように設定

fig.yml
docker/figで起動した環境で日本語が扱えない問題の修正。
mysqld_safeの引数で指定する形にした。
=> Docker: MariaDB charset options

server/app/honor/RankingTop.scala
空の提督ランキングがある状態でユーザーの称号画面に入ると例外が発生する。
誰も図鑑を登録してない場合等。
`head`ダメゼッタイ(論理的に例外が起きない場合を除く)
=> Fix exception with empty ranking

server/app/ranking/FirstShipRate.scala
誰も登録していない状態で艦娘ランキングを開くと例外。
`sqls.in`を使えばコレクションが空の場合には`where false`にしてくれる。
=> Fix SQL syntax error `where ... in ()`

update/src/main/java/Connection.java
ダウンロード中のエラーには対処出来るはず。
これで #175 の症状が軽減されれば良いが。（おそらく根本的な対処では無い）
=> ファイルダウンロード時に一時ファイルを使用するように変更

client/src/main/scala/com/ponkotuy/http/MFGHttp.scala
艦これサーバーとの通信は無関係。
起動時に java -DproxyHost=localhost -DproxyPort=8888  -jar MyFleetGirls.jar
とか指定すると localhost:8888 な Proxy に接続に行きますよ。
指定しない場合は Proxy 使用しないので既存の動作に影響は無い。
=> MyFleetGirls Server への通信に Proxy を設定出来るように

server/app/controllers/Common.scala
もっと自然な英語になるようにしました。
* RequireをRequiredに変換して文の最後へ。
* Failedを文の最後へ。
* Old Authentication -> Old Protocol Authentication
- Protocolを付加。
* Auth Data -> Authentication Data
- `Auth` という単語はないようです。`Auth.` ならOK。
と、ここまでやってみてエラーメッセージは日本語で来た方が良いかも知れないですね…。
#213 にもありますし。
もしくはI18N対応するとかでしょうか。（ScalaのI18N事情をよく知らないです）
=> Fix authentication error messages

client/src/main/scala/com/ponkotuy/proxy/FinagleProxy.scala
プロキシがリクエストを出す時にクエリパラメータがごっそりなくなってて専ブラとの連携が困難だったので修正しました。お使いいただければ幸いです。
=> Fix proxy request URI

server/app/assets/javascript/from_ship.coffee
```
https://myfleet.moe/entire/sta/from_ship#query=大鯨&ship=184
```
https://github.com/ponkotuy/MyFleetGirls/blob/9f66a4cecbcec3e8a5778556fb9285376af86816/server/app/assets/javascript/delete_fav.coffee#L33 と同じで入れるときにエンコード
=> URLのhashのqueryをエンコードするようにした

.travis.yml
travis_wait を使うと良いらしいけど、使い方はこれであってるのだろうか。
http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received
=> Travis CI がタイムアウトするので回避設定

server/app/views/user/ship.scala.html
tablesorterは安定なソートを行うので、tr要素を艦のsortno, 艦固有のIDでソートされるようにしました。
DBから読みだす際にorderByしてもよかったのですが、クエリが他所でも使われているようだったのでやめました。
tablesorter 2.16以降はtd要素のdata-text属性を優先して参照するのを利用しています。
厳密にテストしたわけではありませんが、特にバージョンアップに伴う不具合はないように思えます。
マイナスしているのはページ表示後、「艦種」ヘッダを最初にクリックしたときにゲーム内と同様の並び順にするためです。
=> レベル、艦種ソートの結果をゲーム内と同様にする

server/app/models/join/ShipParameter.scala
端数切捨てのタイミングの違いにより、小破状態を通常状態と誤判定する場合がある事の修正です。
例えば最大HPが 10 の時は 3/4 の 7.5 ⇒ 端数切捨てで 7 以下が小破状態ですが、
10 / 4 で一旦端数の切捨てが行われる為、それの 3 倍で 6 以下を小破と判定していました。
=> 小破判定を誤る場合があるのを修正

client/src/main/scala/com/ponkotuy/proxy/FinagleProxy.scala
現状 MyFleetGirls Proxy は艦これサーバーからの応答内容にかかわらず、クライアント（ 主にブラウザ ）に gzip 圧縮して送っている。
現実問題として Proxy より下位はローカルでの通信を想定するのでオーバーヘッドこそあれ、メリットはほぼ無い。
艦これサーバーからの応答内容に合わせる案もあるが netty 実装を掘り下げないとならない為、暫定的に上記対策を提案する。
=> Proxy サーバーからのレスポンスを gzip/deflate 圧縮しないように変更。

client/src/main/resources/reference.conf, client/src/main/scala/com/ponkotuy/config/ClientConfig.scala
Fix #253 
* reference.confにデフォルト設定を用意してfallback
* application.confが存在しなかった場合、reference.confを元に自動生成
=> [Client]デフォルトのconfを用意する #253

project/Build.scala
`sbt downLib` で jar ファイルが存在しない場合のみダウンロードを行うようにしてみました。
```
$ sbt downLib
[info] Loading project definition from /Users/zaneli/ws/MyFleetGirls/project
[info] Set current project to my-fleet-girls (in build file:/Users/zaneli/ws/MyFleetGirls/)
[info] downloading https://www.free-decompiler.com/flash/download/ffdec_5.3.0_lib.jar ...
$ sbt downLib
[info] Loading project definition from /Users/zaneli/ws/MyFleetGirls/project
[info] Set current project to my-fleet-girls (in build file:/Users/zaneli/ws/MyFleetGirls/)
[info] ffdec_5.3.0_lib.jar has already been downloaded
$ rm server/lib/ffdec_5.3.0_lib.jar
$ sbt downLib
[info] Loading project definition from /Users/zaneli/ws/MyFleetGirls/project
[info] Set current project to my-fleet-girls (in build file:/Users/zaneli/ws/MyFleetGirls/)
[info] …
```
=> Download lib if and only if the file don't exists

.travis.yml, README.org, project/Build.scala
CommandよりTaskの方が使い勝手がよいのでTask使おう。
serverのコンパイル前にdownLibを自動で実行するようにした。
startは元がCommandなのでTaskにできない。
(Playのstartは非推奨でtestProdに変更されている。masterでは更にtestProdが非推奨でrunProdに)
=> Avoid sbt command

client/src/main/scala/com/ponkotuy/config/ClientConfig.scala, client/src/main/scala/com/ponkotuy/proxy/LittleProxy.scala
Clientのapplication.confに
```
```
と書いてあるにも関わらず空文字列でlocalhostのみ受け付けるようになっているので修正
=> Fix proxy InetAddress

client/build.sbt, client/src/main/resources/logback.xml
Windows 7 / OS X での動作は確認済み。
ログファイルへのエスケープシーケンスの混入は戸惑われたのでとりあえずはやらず。
=> コンソールへのログ出力をカラーリングする

client/build.sbt
#374 に関連して。
Commons-HttpClient が Log4j を使用している。
SLF4J 側で用意されている log4j-over-slf4j アダプターを読み込ませることで切り替えられる。
=> Log4j の出力を SLF4J に切り替える。 （ refs #374 ）

client/src/main/scala/com/ponkotuy/proxy/LittleProxy.scala, client/src/main/scala/com/ponkotuy/proxy/LoggingActivityTracker.scala
Log を取る為の ActivityTracker を追加する。
これにより client -> proxy -> server -> proxy -> client の流れが可視化する。
=> 各 Request/Response をログに記録するように。

server/conf/db/migration/default/V146__add_cell_info.sql
E6後半に辿りついたので、抜けていたE6後半部分の海域情報です。
E6前半のボスマスHのボスフラグを立て忘れたので、それも修正しています。
=> 2017夏イベント E6後半の海域情報追加。

library/src/main/scala/com/ponkotuy/value/ShipIds.scala, server/app/tool/AntiAirCutin.scala
・鬼怒改二, 由良改二, 文月改二のカットインを追加
・高射装置付き扱いに 5inch連装砲 Mk.28 mod.2 を追加
Scalaがよく判っていないので変な事をしてたらすみません。
=> 対空カットインの更新

server/app/views/sta/search_snap.scala.html, server/app/views/user/snapshot.scala.html
データ自体は取れていて、現状問題が出ているのはスナップショットの表示部分だけみたいなので、こんな修正でいいと思うのですがどうでしょうか。
以前からある補強増設スロットに対応していないのに、現状武蔵改二のみにしかない第5スロットに対応するというのも微妙ですが。
=> 武蔵改二の第5スロット対応
